### PR TITLE
Add ClickHouse connection

### PR DESCRIPTION
**Pull request by lamr02n**
All the connectors for ClickHouse as well as the insert operations were added. The database now receives information regarding timestamps, messages and more about Loglines and Batches.

### CODE REVIEW

**Comment by lamr02n** [comment]
The PR is in the final stages. However, some inserts are still missing and further testing is necessary before it is ready.

**Review by stefanDeveloper — APPROVED** [review]
Looks good to me :)

**Review by stefanDeveloper — APPROVED** [review]

**Comment by stefanDeveloper** [comment]
Do you know why windows tests are still failing?

**Comment by lamr02n** [comment]
> Do you know why windows tests are still failing?

Not exactly, but it might have to do with caches. We could try to clear those.

**Comment by lamr02n** [comment]
I will do a couple of manual integration tests before merging to ensure everything still works as it should.

**Comment by stefanDeveloper** [comment]
> I will do a couple of manual integration tests before merging to ensure everything still works as it should.

After your integration tests, please put the merge request in ready to merge. I will merge it accordingly.

**Comment by lamr02n** [comment]
Closes #11.

**Review by stefanDeveloper — APPROVED** [review]

**Pull request merged**
